server:
  port: ${PORT:8080}

spring:
  application:
    name: zyger-manufacturing-erp-java
  datasource:
    url: jdbc:h2:mem:zyger_erp;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5435}/${DB_NAME:zyger_erp_demo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver


  sql:
    init:
      mode: always
      continue-on-error: true

