export const CRM_ENTITIES = {
  leads: {
    title: 'CRM Leads',
    singular: 'Lead',
    numberField: 'lead_no',
    dateField: 'lead_date',
    subtitle: 'Capture leads, follow-ups, source, priority and current sales stage',
    columns: [
      { key: 'lead_no', label: 'Lead No' },
      { key: 'lead_date', label: 'Lead Date' },
      { key: 'company_name', label: 'Company' },
      { key: 'contact_person', label: 'Contact' },
      { key: 'phone', label: 'Phone' },
      { key: 'stage', label: 'Stage' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'lead_no', label: 'Lead Number', type: 'text', readOnly: true },
      { name: 'lead_date', label: 'Lead Date', type: 'date' },
      { name: 'company_name', label: 'Company Name', type: 'text', required: true },
      { name: 'contact_person', label: 'Contact Person', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'source', label: 'Lead Source', type: 'select', options: ['Website', 'Referral', 'Phone Call', 'Email', 'Campaign', 'Walk-in'] },
      { name: 'stage', label: 'Stage', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Proposal', 'Won', 'Lost'] },
      { name: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Urgent'] },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
      { name: 'expected_value', label: 'Expected Value', type: 'number' },
      { name: 'next_followup_date', label: 'Next Follow-up', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Converted', 'Closed'] },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  enquiries: {
    title: 'CRM Enquiries',
    singular: 'Enquiry',
    numberField: 'enquiry_no',
    dateField: 'enquiry_date',
    subtitle: 'Convert lead requirements into enquiry records for quotation follow-up',
    columns: [
      { key: 'enquiry_no', label: 'Enquiry No' },
      { key: 'enquiry_date', label: 'Date' },
      { key: 'customer_name', label: 'Customer' },
      { key: 'contact_person', label: 'Contact' },
      { key: 'phone', label: 'Phone' },
      { key: 'estimated_value', label: 'Estimate' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'enquiry_no', label: 'Enquiry Number', type: 'text', readOnly: true },
      { name: 'enquiry_date', label: 'Enquiry Date', type: 'date' },
      { name: 'lead_id', label: 'Lead ID Reference', type: 'number' },
      { name: 'customer_name', label: 'Customer Name', type: 'text', required: true },
      { name: 'contact_person', label: 'Contact Person', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'estimated_value', label: 'Estimated Value', type: 'number' },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Quoted', 'Won', 'Lost', 'Closed'] },
      { name: 'requirement', label: 'Requirement', type: 'textarea' },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  quotations: {
    title: 'CRM Quotations',
    singular: 'Quotation',
    numberField: 'quotation_no',
    dateField: 'quotation_date',
    subtitle: 'Prepare quotation summary, validity, value and approval status',
    columns: [
      { key: 'quotation_no', label: 'Quotation No' },
      { key: 'quotation_date', label: 'Date' },
      { key: 'customer_name', label: 'Customer' },
      { key: 'subject', label: 'Subject' },
      { key: 'total_amount', label: 'Total' },
      { key: 'valid_until', label: 'Valid Until' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'quotation_no', label: 'Quotation Number', type: 'text', readOnly: true },
      { name: 'quotation_date', label: 'Quotation Date', type: 'date' },
      { name: 'enquiry_id', label: 'Enquiry ID Reference', type: 'number' },
      { name: 'customer_name', label: 'Customer Name', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'subtotal', label: 'Sub Total', type: 'number' },
      { name: 'tax_amount', label: 'Tax Amount', type: 'number' },
      { name: 'total_amount', label: 'Total Amount', type: 'number' },
      { name: 'valid_until', label: 'Valid Until', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Sent', 'Accepted', 'Rejected', 'Expired'] },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  campaigns: {
    title: 'CRM Campaigns',
    singular: 'Campaign',
    numberField: 'campaign_no',
    dateField: 'start_date',
    subtitle: 'Plan marketing campaigns, budgets, audience and campaign status',
    columns: [
      { key: 'campaign_no', label: 'Campaign No' },
      { key: 'campaign_name', label: 'Campaign' },
      { key: 'campaign_type', label: 'Type' },
      { key: 'start_date', label: 'Start' },
      { key: 'end_date', label: 'End' },
      { key: 'budget', label: 'Budget' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'campaign_no', label: 'Campaign Number', type: 'text', readOnly: true },
      { name: 'campaign_name', label: 'Campaign Name', type: 'text', required: true },
      { name: 'campaign_type', label: 'Campaign Type', type: 'select', options: ['Email', 'SMS', 'Call', 'Social', 'Event', 'Digital Ads'] },
      { name: 'start_date', label: 'Start Date', type: 'date' },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'budget', label: 'Budget', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['Planned', 'Running', 'Paused', 'Completed', 'Cancelled'] },
      { name: 'target_audience', label: 'Target Audience', type: 'textarea' },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  contacts: {
    title: 'CRM Contacts',
    singular: 'Contact',
    numberField: 'contact_no',
    dateField: 'created_at',
    subtitle: 'Maintain customer/prospect contact list connected with CRM activity',
    columns: [
      { key: 'contact_no', label: 'Contact No' },
      { key: 'contact_name', label: 'Contact' },
      { key: 'company_name', label: 'Company' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'city', label: 'City' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'contact_no', label: 'Contact Number', type: 'text', readOnly: true },
      { name: 'contact_name', label: 'Contact Name', type: 'text', required: true },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'state', label: 'State', type: 'text' },
      { name: 'source', label: 'Source', type: 'select', options: ['Website', 'Referral', 'Campaign', 'Existing Customer', 'Manual Entry'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Do Not Contact'] },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
}

export const CRM_ENTITY_ORDER = ['leads', 'enquiries', 'quotations', 'campaigns', 'contacts']
