export const PROCESS_CONFIG = {
  so: {
    title: 'Sales Order',
    createTitle: 'Create Sales Order',
    subtitle: 'Sales -> SO process flow',
    numberLabel: 'SO Number',
    menuLabel: 'Sales Order (SO)',
    sourceLabel: 'Customer / Enquiry Ref',
  },
  wo: {
    title: 'Work Order',
    createTitle: 'Create Work Order',
    subtitle: 'Production -> WO process flow',
    numberLabel: 'WO Number',
    menuLabel: 'Work Order (WO)',
    sourceLabel: 'SO / BOM Ref',
  },
  po: {
    title: 'Purchase Order',
    createTitle: 'Create Purchase Order',
    subtitle: 'Purchase -> PO process flow',
    numberLabel: 'PO Number',
    menuLabel: 'Purchase Order (PO)',
    sourceLabel: 'PR / Supplier Ref',
    listColumns: ['poNumber', 'prqNo', 'poDate', 'woOrder', 'vendor', 'inward', 'poType', 'totalQty', 'createdBy', 'status', 'currentApprover', 'approvalStatus'],
  },
  pr: {
    title: 'Purchase Request',
    createTitle: 'Create Purchase Request',
    subtitle: 'Purchase Request (PR) for material planning',
    numberLabel: 'PR Number',
    menuLabel: 'Purchase Request (PR)',
    sourceLabel: 'Order Number',
  },
  bom: {
    title: 'Bill of Material',
    createTitle: 'Create Bill of Material',
    subtitle: 'BOM mapping for production and MRP',
    numberLabel: 'BOM Number',
    menuLabel: 'Bill of Material (BOM)',
    sourceLabel: 'Parent Item / WO Ref',
  },
  mrp: {
    title: 'Material Requirement Planning',
    createTitle: 'Create Material Requirement Planning',
    subtitle: 'MRP reservation and available stock planning',
    numberLabel: 'MRP Number',
    menuLabel: 'Material Requirement Planning (MRP)',
    sourceLabel: 'Order Number',
  },
  production: {
    title: 'Production',
    createTitle: 'Create Production Entry',
    subtitle: 'Production issue, receipt and completion tracking',
    numberLabel: 'Production Number',
    menuLabel: 'Production',
    sourceLabel: 'WO / MRP Ref',
  },
  routesheet: {
    title: 'Routesheet',
    createTitle: 'Create Routesheet',
    subtitle: 'Production -> Routesheet after BOM / WO',
    numberLabel: 'Routesheet Number',
    menuLabel: 'Routesheet',
    sourceLabel: 'WO / BOM Ref',
  },
  'raw-material-issue': {
    title: 'Raw Material Issue',
    createTitle: 'Create Raw Material Issue',
    subtitle: 'Stores -> Raw material issue to production',
    numberLabel: 'RMI Number',
    menuLabel: 'Raw Material Issue',
    sourceLabel: 'WO / Routesheet Ref',
  },
  'fg-stock': {
    title: 'Finished Goods Stock',
    createTitle: 'Create FG Stock Entry',
    subtitle: 'Stores -> Finished goods stock receipt',
    numberLabel: 'FG Stock Number',
    menuLabel: 'FG Stock',
    sourceLabel: 'Production / Inspection Ref',
  },
  'general-dc': {
    title: 'General DC',
    createTitle: 'Create General DC',
    subtitle: 'Stores -> General DC returnable / non-returnable flow',
    numberLabel: 'DC Number',
    menuLabel: 'General DC',
    sourceLabel: 'Receipt / PO Inward / Reference',
  },
  iar: {
    title: 'Issue Against Receipt',
    createTitle: 'Create IAR',
    subtitle: 'Stores -> Issue Against Receipt returnable flow',
    numberLabel: 'IAR Number',
    menuLabel: 'Issue Against Receipt',
    sourceLabel: 'Receipt Return / Reference',
  },
  rai: {
    title: 'Received Against Issue',
    createTitle: 'Create RAI',
    subtitle: 'Stores -> Received Against Issue returnable flow',
    numberLabel: 'RAI Number',
    menuLabel: 'Received Against Issue',
    sourceLabel: 'Returnable DC / Reference',
  },
  'jo-inward': {
    title: 'JO Inward',
    createTitle: 'Create JO Inward',
    subtitle: 'Stores -> JO Inward against routesheet / JO DC',
    numberLabel: 'JO Inward Number',
    menuLabel: 'JO Inward',
    sourceLabel: 'Route Sheet / JO DC',
  },
  'supplier-invoice': {
    title: 'Supplier Invoice',
    createTitle: 'Create Supplier Invoice',
    subtitle: 'Stores -> Supplier invoice against inward / PO',
    numberLabel: 'Supplier Invoice Number',
    menuLabel: 'Supplier Invoice',
    sourceLabel: 'PO / Inward Reference',
  },
}

export const PROCESS_ORDER_TYPES = [
  'Sales Order',
  'Work Order',
  'Purchase Order',
  'Job Work',
  'Production',
  'Routesheet',
  'Raw Material Issue',
  'Finished Goods Stock',
  'Stock',
  'Returnable',
  'Non Returnable',
  'Received Against Issue',
  'Issue Against Receipt',
]

export const PROCESS_DEPARTMENTS = ['Stores', 'Purchase', 'Production', 'Quality', 'Planning', 'Sales']
export const PROCESS_STATUS = ['Open', 'In Progress', 'Closed', 'Cancelled']
export const PROCESS_APPROVAL_STATUS = ['Pending', 'Approved', 'Rejected']
export const PO_TYPES = ['Regular', 'Job Work', 'Import', 'Service', 'Capital']
export const TAX_NAMES = ['CGST', 'IGST', 'SGST', 'GST 5%', 'GST 12%', 'GST 18%', 'GST 28%']
